---
# tasks file for httpdrole
- name: installing the httpd software
  package:
      name: httpd 
      state: present

- name: copying pages
  copy: 
      src: /root/hi.txt
      dest: /var/www/html/
  notify: me

